rath3r_site_homepage:
    path:     /
    defaults:
      _controller: Rath3rSiteBundle:Home:index

rath3r_site_aboutpage:
    path:     /about
    defaults:
      _controller: Rath3rSiteBundle:About:index

rath3r_site_trainspage:
    path:     /trians
    defaults:
      _controller: Rath3rSiteBundle:Trains:index

_index:
    path:     index
    defaults: { _controller: Rath3rSiteBundle:About:Index }
