#!/bin/sh

PROGPATH=$(dirname $_)

LIST=$(find $PROGPATH/plugins -type f -maxdepth 1 -name "*.js" -print)

for path in $LIST
do

	arr=$(echo $path | tr "/" "\n")

	for x in $arr
	do
		LAST=$x
	done

	echo "File: $path"

	exec<$path
	oneLineFile=
	while read line
	do
		oneLineFile="$oneLineFile $PROGPATH/plugins/$line"
		echo "  --> $PROGPATH/plugins/$line"
	done
	oneLineFile="$oneLineFile $PROGPATH/plugins/$line"
	echo "  --> $PROGPATH/plugins/$line"

	eval cat$oneLineFile > $PROGPATH/../../../wwwroot/js/$LAST

	echo "  ==> Output: $PROGPATH/../../../wwwroot/js/$LAST"

done


LIST=$(find $PROGPATH/scripts -type f -maxdepth 1 -name "*.js" -print)

for path in $LIST
do

	arr=$(echo $path | tr "/" "\n")

	for x in $arr
	do
		LAST=$x
	done

	echo "File: $path"

	exec<$path
	oneLineFile=
	while read line
	do
		oneLineFile="$oneLineFile $PROGPATH/scripts/$line"
		echo "  --> $PROGPATH/scripts/$line"
	done
	oneLineFile="$oneLineFile $PROGPATH/scripts/$line"
	echo "  --> $PROGPATH/scripts/$line"

	eval cat$oneLineFile > $PROGPATH/../../../wwwroot/js/$LAST

	catfile=$PROGPATH/../../../wwwroot/js/$LAST
    echo "
/*

 Page main APP
 (c) Thomas Meehan

 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !!                                               !!
 !!             Development version               !!
 !!                                               !!
 !!        !!! DO NOT EDIT THIS FILE !!!          !!
 !!                                               !!
 !!  Edit js asset files and run compile script.  !!
 !!                                               !!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

*/


$(cat $catfile)" > $catfile

	echo "  ==> Output: $PROGPATH/../../../wwwroot/js/$LAST"

done
